// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5CSTPDiex06CaP0JjpR5Bag5Rf7-bb8g',
    appId: '1:963972220755:web:41c41585c6a5a27e7b83a6',
    messagingSenderId: '963972220755',
    projectId: 'moodscape-bf678',
    authDomain: 'moodscape-bf678.firebaseapp.com',
    storageBucket: 'moodscape-bf678.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4XVDHElLsNnnLw69Q9MwodCjfpOj4AoQ',
    appId: '1:963972220755:android:e348efe218f20a837b83a6',
    messagingSenderId: '963972220755',
    projectId: 'moodscape-bf678',
    storageBucket: 'moodscape-bf678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr92FiPpd6dFweHXAh1Y_PXMFMhz6aM2k',
    appId: '1:963972220755:ios:072f94ef39a716e47b83a6',
    messagingSenderId: '963972220755',
    projectId: 'moodscape-bf678',
    storageBucket: 'moodscape-bf678.firebasestorage.app',
    iosBundleId: 'com.example.moodscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr92FiPpd6dFweHXAh1Y_PXMFMhz6aM2k',
    appId: '1:963972220755:ios:072f94ef39a716e47b83a6',
    messagingSenderId: '963972220755',
    projectId: 'moodscape-bf678',
    storageBucket: 'moodscape-bf678.firebasestorage.app',
    iosBundleId: 'com.example.moodscape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5CSTPDiex06CaP0JjpR5Bag5Rf7-bb8g',
    appId: '1:963972220755:web:7a54f95cce49be6b7b83a6',
    messagingSenderId: '963972220755',
    projectId: 'moodscape-bf678',
    authDomain: 'moodscape-bf678.firebaseapp.com',
    storageBucket: 'moodscape-bf678.firebasestorage.app',
  );
}
